# Generated by Django 2.0.7 on 2020-04-14 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('calle', models.CharField(max_length=120, null=True)),
                ('colonia', models.CharField(max_length=120, null=True)),
                ('ciudad', models.CharField(max_length=120, null=True)),
                ('estado', models.CharField(max_length=30, null=True)),
                ('cp', models.CharField(max_length=5, null=True)),
                ('default_adress', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status_orden', models.CharField(blank=True, max_length=40, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_order_id', models.CharField(blank=True, max_length=120, null=True)),
                ('cart_json', models.TextField(blank=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('divisa', models.CharField(blank=True, max_length=100, null=True)),
                ('client_msg', models.TextField(blank=True)),
                ('oxxo_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_transf', models.CharField(blank=True, max_length=100, null=True)),
                ('clabe_transf', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Adress')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='adress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
