export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_ANONYMOUS_CART = "AUTH_ANONYMOUS_CART"
export const AUTH_DELETE_ANONYMOUS_CART = "AUTH_DELETE_ANONYMOUS_CART"
export const AUTH_START_GET_CLIENT_DATA = "AUTH_START_GET_CLIENT_DATA"
export const AUTH_GET_CLIENT_DATA = "AUTH_GET_CLIENT_DATA"
export const AUTH_SUCCESS_GET_CLIENT_DATA = "AUTH_SUCCESS_GET_CLIENT_DATA"

export const CART_START = "CART_START";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_PRODUCT_ADDED = "CART_PRODUCT_ADDED";
export const CART_DELETE_ITEM = "CART_DELETE_ITEM";
export const CART_FLUSH = "CART_FLUSH";
export const CART_FAIL = "CART_FAIL";

export const ORDER_PAYMENT_GET_DETAIL = "ORDER_PAYMENT_DETAIL"
export const ORDER_PAYMENT_GET_SUCCESS = "ORDER_PAYMENT_GET_SUCCESS"
export const START_ORDER_PAYMENT = "START_ORDER_PAYMENT" 
export const ORDER_PAYMENT_POST_DETAIL = "ORDER_PAYMENT_POST"
export const ORDER_PAYMENT_SUCCESS = "ORDER_PAYMENT_SUCCESS" 
export const ORDER_PAYMENT_FAIL = "ORDER_PAYMENT_FAIL" 